version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - misspell

settings:
  revive:
    rules:
      - name: exported

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  tests: true
  skip-dirs:
    - vendor
