version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
